spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/BootingDB?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    #MacBook    url: jdbc:mysql://127.0.0.1:3306/BootDB?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bootuser
    password: boot1234

#  datasource:

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: bootuser
#    password: boot1234

  batch:
    jdbc:
      initialize-schema: always